### PR TITLE
Huge mod file system rework — MERGE READY (bugs are possible)

### PR DESCRIPTION
**Pull request by zipliks**
- Fixed stasis bag issue
- Fixed Russian sepsis localization
- Fixed Russian/English items descriptions/names
- XML format
- Changed some ids to prevent further issues

### CODE REVIEW

**Comment by hnappinn** [comment]
Screenshot_15

**Comment by zipliks** [comment]
Seems I'll not be able to resolve that issue since there is no more **_Advanced Medicine/Images/InGameItemIconAtlas.png_** or **_Advanced Medicine/Images/InventoryItemIconAtlas.png_** so that's what I'm talking about titling this pr "Huge mod file system rework"

On the other hand, I was able to fix some conflict and path errors/crashes.

Solution: remove all the current files and replace it with pull request.
Possible issues: literally everything can lead to an error.

**Comment by hnappinn** [comment]
Are you sure it's worth changing id everywhere? There are many problems with this. All things with the old ID in the campaign will be lost, and in the submarines too

**Comment by zipliks** [comment]
It's up to you, I just recommend changing all the current IDs to prevent conflicts with other mods. Anyway, I will continue to update this pr until a decision is made.

My current goal is wiki-like web page

**Comment by lvvova1** [comment]
Thank you for PR

I looked at your PR, and here some issues:

1) You moved files from Advanced Medicine to "root" folder(and filelist), it's bad idea because here also Source folder should not be in the game. Yep we can just don't touch this folder when they were separate it was more convenient in my opinion.
2) I am not very experienced in modding, but I don't see any benefit in changing file names, for example I can't imagine a situation when `Mods/Advanced Medicine/Images/AfflictionIconAtlas.png` path can cause conflict with other mod, because in path we write Mods/Advanced Medicine.
(But anyway your naming more readable)

About id's as hnappinn says, everything will disappear, I think we can change ids when make "big" update.

**Comment by zipliks** [comment]
1. The Source folder will not be in the game, since the mod author decides which files to add to Steam Workshop. So it's only for repo. 
2. Source folder is not stated it the filelist.xml so the game can't even detect that folder (except files inside it but that doesn't matter as stated in the first article)
3. The file names have changed to simplify console manipulations and sprite editor. For example, it would be easier to spawn something playing with a modpack using mod prefix such as "am_". As about **editsprites** there are several "IconAtlases", at least 2 of them are from the vanilla game. 

As we discussed it on the discord server, it would be better releasing such a big updates with an announce to let players deconstruct "yet-not-obsolete" items

**Pull request closed without merging**
